package be.corentinvanhaeren.sandwix.ui.theme

import androidx.compose.ui.graphics.Color

val SandwixPrimaryLight = Color(0xFF765A00)
val SandwixOnPrimaryLight = Color(0xFFFFFFFF)
val SandwixPrimaryContainerLight = Color(0xFFF4C43F)
val SandwixOnPrimaryContainerLight = Color(0xFF493600)
val SandwixSecondaryLight = Color(0xFF6A5D3E)
val SandwixOnSecondaryLight = Color(0xFFFFFFFF)
val SandwixSecondaryContainerLight = Color(0xFFEEDFAF)
val SandwixOnSecondaryContainerLight = Color(0xFF231B04)
val SandwixTertiaryLight = Color(0xFF416745)
val SandwixOnTertiaryLight = Color(0xFFFFFFFF)
val SandwixTertiaryContainerLight = Color(0xFFC3EBC0)
val SandwixOnTertiaryContainerLight = Color(0xFF002109)
val SandwixErrorLight = Color(0xFFB7151A)
val SandwixOnErrorLight = Color(0xFFFFFFFF)
val SandwixBackgroundLight = Color(0xFFFFF8F1)
val SandwixOnBackgroundLight = Color(0xFF1F1B12)
val SandwixSurfaceLight = Color(0xFFFFFBFF)
val SandwixOnSurfaceLight = Color(0xFF1C1B1B)
val SandwixSurfaceVariantLight = Color(0xFFEAE1D6)
val SandwixOnSurfaceVariantLight = Color(0xFF4B463E)
val SandwixOutlineLight = Color(0xFF7C766D)

val SandwixPrimaryDark = Color(0xFFFFD772)
val SandwixOnPrimaryDark = Color(0xFF3E2E00)
val SandwixPrimaryContainerDark = Color(0xFF5A4400)
val SandwixOnPrimaryContainerDark = Color(0xFFFFD772)
val SandwixSecondaryDark = Color(0xFFD6C59E)
val SandwixOnSecondaryDark = Color(0xFF392F14)
val SandwixSecondaryContainerDark = Color(0xFF51462A)
val SandwixOnSecondaryContainerDark = Color(0xFFF3E1B7)
val SandwixTertiaryDark = Color(0xFFA7D1A8)
val SandwixOnTertiaryDark = Color(0xFF13371B)
val SandwixTertiaryContainerDark = Color(0xFF2A4F2F)
val SandwixOnTertiaryContainerDark = Color(0xFFC3EBC0)
val SandwixErrorDark = Color(0xFFFFB4AB)
val SandwixOnErrorDark = Color(0xFF690006)
val SandwixBackgroundDark = Color(0xFF17130B)
val SandwixOnBackgroundDark = Color(0xFFEBE1D3)
val SandwixSurfaceDark = Color(0xFF141313)
val SandwixOnSurfaceDark = Color(0xFFE6E2E0)
val SandwixSurfaceVariantDark = Color(0xFF4B463E)
val SandwixOnSurfaceVariantDark = Color(0xFFCDC5BB)
val SandwixOutlineDark = Color(0xFF969086)

val OrderBlue = Color(0xFF0C58E4)
val OrderGreen = Color(0xFF008730)
val OrderOrange = Color(0xFFF59E0B)
